### PR TITLE
remove unnecessary wrapping div

### PR DESCRIPTION
**Pull request by notwaldorf**
It doesn't do anything, other than make it impossible to actually style the listbox. :)

### CODE REVIEW

**Comment by notwaldorf** [comment]
Was this passing on master? All the tests look fine on Safari 9 :/

**Comment by addyosmani** [comment]
This looks like it should be passing..

**Comment by cdata** [comment]
Kicked CI. Either way the failure was in an `afterEach`, which should be benign.

**Comment by cdata** [comment]
I vote to merge this, `afterEach` failure is flakey. LGTM :+1:

**Comment by notwaldorf** [comment]
Fanks! Merging!

**Pull request merged**
